[project]
name = "ezexample"
version = "0.1.0"
description = "ezExample using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[google-genai,tools]==1.3.0",
]

[project.scripts]
ezexample = "ezexample.main:run"
run_crew = "ezexample.main:run"
train = "ezexample.main:train"
replay = "ezexample.main:replay"
test = "ezexample.main:test"
run_with_trigger = "ezexample.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
